version: '3'
services:
    php:
        build: ./docker/php
        env_file: '.env'
        volumes:
        - './:/var/www/mercure-chat:rw'

    nginx:
        build: ./docker/nginx
        ports:
        - 81:80
        volumes:
        - './public/:/var/www/mercure-chat/public'

    database:
        image: mysql:8
        ports:
        - 3306:3306
        volumes:
        - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secretpass
            MYSQL_USER: astro
            MYSQL_PASSWORD: secretpass
            MYSQL_DATABASE: astrochat

    mercure:
        image: dunglas/mercure
        ports:
        - 3000:80
        environment:
            PUBLISH_URL: '${MERCURE_PUBLISH_URL}'
            JWT_KEY: '${MERCURE_JWT_KEY}'
            MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
            MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
            ALLOW_ANONYMOUS: '${MERCURE_ALLOW_ANONYMOUS}'
            CORS_ALLOWED_ORIGINS: '${MERCURE_CORS_ALLOWED_ORIGINS}'
            PUBLISH_ALLOWED_ORIGINS: '${MERCURE_PUBLISH_ALLOWED_ORIGINS}'

    caddy:
        image: caddy
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile:ro
        ports:
            - "80:80"


volumes:
  db-data:
